### ISSUE TITLE
패키지 임포트를 수정해주세요

### ISSUE THREAD

**Issue by sigmadream** [alls7554/ks-web#1]
https://github.com/alls7554/ks-web/blob/1bece36ff87d9647dea985e6d7fdf80f70efa8f8/src/main/java/com/cheoloh/app/Controller/Controller.java#L5

**Comment by alls7554** [comment]
다음과 같이 수정하면 될까요??? IndexController.java 전문입니다!

package com.cheoloh.app.Controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class IndexController {
    @GetMapping("/")
    public String index(){
        return "index";
    }
}

**Comment by sigmadream** [comment]
네, 그렇게 수정하시면 됩니다. 감사합니다.

**Comment by alls7554** [comment]
감사합니다!!!
