### ISSUE TITLE
과제 #2 수고하셨습니다.

### ISSUE THREAD

**Issue by sigmadream** [alls7554/ks-web#2]
과제 #2 수고하셨습니다.

**Comment by alls7554** [comment]
감사합니다!! 이슈 클로즈 해도 되겠습니까?

**Comment by sigmadream** [comment]
네 Close 하세요

2020년 5월 5일 (화) 오후 10:46, alls7554 <notifications@github.com>님이 작성:

**Comment by alls7554** [comment]
감사합니다! 편안한 휴식 되세요 :)
